name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev --extras service

      - name: Run ruff
        run: poetry run ruff check .

      - name: Run basedpyright
        run: poetry run basedpyright

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install package
        run: pip install .

      - name: Run CLI help
        run: gerber_to_scad -h
