name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run ruff
        run: poetry run ruff check .

      - name: Run basedpyright
        run: poetry run basedpyright
